# -*- coding: utf-8 -*-
"""Sales Data.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11JPuapmaLsBHj2nsiK2hTpvfqXjns55P
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline
import seaborn as sns

import pandas as pd

# Load the dataset
df = pd.read_csv("/content/Sales Data.csv")

df.shape

df.head()

# Remove duplicate rows
df.drop_duplicates(inplace=True)

# Drop 'Unnamed' columns (e.g., 'Unnamed: 0')
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]

df.info()

df['Order Date'] = pd.to_datetime(df['Order Date'])

print(df.isnull().sum())  # Check for missing values
print(df.duplicated().sum())  # Check for duplicate rows

sales_by_city = df.groupby('City')['Sales'].sum()
print(sales_by_city)

df['Order ID'] = pd.to_numeric(df['Order ID'], downcast='integer')
df['Price Each'] = pd.to_numeric(df['Price Each'], downcast='float')

total_revenue = df['Sales'].sum()
print(total_revenue)

top_revenue_products = df.groupby('Product')['Sales'].sum().sort_values(ascending=False)
print(top_revenue_products)

top_quantity_products = df.groupby('Product')['Quantity Ordered'].sum().sort_values(ascending=False)
print(top_quantity_products)

sales_by_city = df.groupby('City')['Sales'].sum().sort_values(ascending=False)
print(sales_by_city)

from google.colab import drive
drive.mount('/content/drive')

sales_by_hour = df.groupby('Hour')['Sales'].sum()
print(sales_by_hour)

import matplotlib.pyplot as plt

plt.bar(sales_by_hour.index, sales_by_hour.values)
plt.xlabel('Hour')
plt.ylabel('Sales')
plt.title('Sales by Hour')
plt.show()

df.head()